server:
  port: 8080
  servlet:
    session:
      # 设置session过期时间，6个小时
      timeout: 21600
#  tomcat:
#    connection-timeout: 18000000

# 选择使用开发环境还是生产环境
spring:
  profiles:
    active: prod

chatgpt:
  api:
    proxy-port: 7890
    proxy-url: 127.0.0.1
    api-key: 你的chatGPT API
    chat-largest-context: 20
