server:
  port: 8080
  servlet:
    session:
      # 设置session过期时间
      timeout: 21600
#  tomcat:
#    connection-timeout: 18000000

spring:
  application:
    name: m-blog-springboot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    url: jdbc:mysql://www.mingzib.xyz:3306/blog?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: blog
    password: MySQL密码
  # redis相关
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # 云服务器地址
    host: 
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 20
        # 最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 5
        # 连接池中的最小空闲连接
        min-idle: 0
    # redis密码
    password: 你的redis密码
    # Redis服务器连接端口
    port: 6379
    # 连接超时时间（毫秒）
    timeout: 1800000
  # 上传文件最大大小
  servlet:
    multipart:
      # 设置单个文件的大小
      max-file-size: 100MB
      # 设置单次请求的文件的总大小
      max-request-size: 100MB

# mybatisPlus设置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 逻辑删除：1表示已删除 0表示未删除
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:/mapper/**/*.xml


gravatar:
  qqEmail: 1940307627@qq.com

# 上传文件
upload:
  # nginx映射本地文件位置
  url: http://www.static.mingzib.xyz/blogUploadFile/
  # 本地文件存储路径
  path: /www/blog/uploadImg/
